### ISSUE TITLE
YTMusic.get_album_browse_id raising `KeyError: 'header'`

### ISSUE THREAD

**Issue by natumbri** [sigma67/ytmusicapi#330] opened 2022-12-22 22:30 UTC
Hi,

When using an authenticated ytmusic client,  `ytmusic.get_album_browse_id(id)`  is causing `nav`  to throw a `KeyError: 'header'` for me (example response here: https://gist.github.com/natumbri/b82b3c3b6933b8c861eab92e3c32f30f).  The other methods work just fine with the authenticated ytmusic client.

No problem with an unauthenticated client: `YTMusic.get_album_browse_id(YTMusic(),id)` works just fine (example response here: https://gist.github.com/natumbri/12c6fe0313cfa49294268fd7982d3a1c)

Seems to happen for all ids, but definitely with this one `OLAK5uy_lUNm1YMm972Rvy0LpDg3ORQFjtN_8oBtc`.

Cheers,
Nik

**Comment by sigma67** [comment] 2023-01-01 20:39
That's strange, I don't have this issue with my account. Have you checked that you're able to access the album in your browser?

https://music.youtube.com/playlist?list=OLAK5uy_lUNm1YMm972Rvy0LpDg3ORQFjtN_8oBtc

**Comment by natumbri** [comment] 2023-01-01 22:21
Yeah, it is odd. The url works fine in my browser, when logged in. 

I'm pretty sure this previously worked just fine for me, too. 

I'll continue to try to work out what happened....

**Comment by sigma67** [comment] 2023-01-27 12:28
Did you run into this issue again or manage to find a root cause? Else I'd go ahead and close this due to lack of reproduceability.

**Comment by natumbri** [comment] 2023-01-27 12:31
To be honest, I haven't looked into it. Go ahead and close; if I run into it again, I can reopen.

Cheers
Nik

**Closed** 2023-01-27 12:32 UTC
