### ISSUE TITLE
Match 'X-Goog-AuthUser' during setup.

### ISSUE THREAD

**Issue by larntz** [sigma67/ytmusicapi#46] opened 2020-07-16 23:52 UTC
Thanks for writing this! I was playing around with it and noticed that during setup it does not copy the number from the request header X-Goog-AuthUser. 

In the pasted headers from firefox contained:

```
X-Goog-AuthUser: 2
```

But the generated header_auth.json was using:

```
"X-Goog-AuthUser": "0"
``` 

This was causing my liked songs, playlists, etc to be pulled from different google account that I don't use with youtube music. 

I have a few google accounts. I'm not sure how google handles all that. This particular account is not a brand account, and I didn't notice this in the docs so thought I'd let you know. 

I noticed the AuthUser number matches this url when selecting the correct account: https://myaccount.google.com/u/2/?pli=1 (the 2 changes to 0 on my default account). 

I changed the value X-Goog-AuthUser to match the firefox request headers and it worked perfectly. 

Thanks again! Let me know if you need more info.

**Comment by sigma67** [comment] 2020-07-17 08:58
Good point, I always used the first account in the list so I didn't notice. Should be an easy fix in `setup.py`.

**Comment by sigma67** [comment] 2020-07-18 14:16
Can you please verify that the issue is fixed with the latest commit?

**Closed** 2020-07-20 09:09 UTC

**Comment by gaganpreet** [comment] 2020-11-01 10:04
Unfortunately this commit wasn't enough, I added `X-Goog-AuthUser` to required_headers to make it work correctly. I'll create a PR shortly with my fix.
