### ISSUE TITLE
New `KeyError` when calling `get_liked_songs()`

### ISSUE THREAD

**Issue by apastel** [sigma67/ytmusicapi#570] opened 2024-04-03 03:18 UTC
**Describe the bug**
`YTMusic.get_liked_songs()` started raising a new `KeyError` today. Mostly likely YTM changed something, I'm assuming. Running ytmusicapi-1.6.0.

Code sample:
```
from ytmusicapi import YTMusic

yt_auth = YTMusic("./oauth.json")
yt_auth.get_liked_songs()
```

Output
```
Traceback (most recent call last):
  File "C:\Users\alexr\dev\ytmusic-deleter\.venv\Lib\site-packages\ytmusicapi\navigation.py", line 101, in nav
    root = root[k]
           ~~~~^^^
KeyError: 'singleColumnBrowseResultsRenderer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\alexr\dev\ytmusic-deleter\test.py", line 4, in <module>
    yt_auth.get_liked_songs()
  File "C:\Users\alexr\dev\ytmusic-deleter\.venv\Lib\site-packages\ytmusicapi\mixins\playlists.py", line 174, in get_liked_songs
    return self.get_playlist("LM", limit)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexr\dev\ytmusic-deleter\.venv\Lib\site-packages\ytmusicapi\mixins\playlists.py", line 109, in get_playlist
    results = nav(response, SINGLE_COLUMN_TAB + SECTION_LIST_ITEM + ["musicPlaylistShelfRenderer"])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexr\dev\ytmusic-deleter\.venv\Lib\site-packages\ytmusicapi\navigation.py", line 105, in nav
    raise type(e)(f"Unable to find '{k}' using path {items!r} on {root!r}, exception: {e}")
KeyError: 'Unable to find \'singleColumnBrowseResultsRenderer\' using path [\'contents\', \'singleColumnBrowseResultsRenderer\', \'tabs\', 0, \'tabRenderer\', \'content\', \'sectionListRenderer\', \'contents\', 0, \'musicPlaylistShelfRenderer\'] on {\'twoColumnBrowseResultsRenderer\': {\'secondaryContents\': {\'sectionListRenderer\': {\'contents\': [{\'musicPlaylistShelfRenderer\': {\'playlistId\': \'LM\', \'contents\': [{\'musicResponsiveListItemRenderer\': {\'trackingParams\': \'CBMQyfQCGAAiEwjhlPOZiqWFAxUDlOUHHbe4Cxo=\', \'thumbnail\': {\'musicThumbnailRenderer\': {\'thumbnail\': {\'thumbnails\': [{\'url\': \'https://lh3.googleusercontent.com/xM8bzhN_pbFY8HyyglVe9XMaDRH5SGqkCnZvMEQ0B4653LkXqGT19k-Uqzv6OiB0LMVoKsRhuHOAh0E=w60-h60-l90-rj\', \'width\': 60, \'height\': 60}, {\'url\': \'https://lh3.googleusercontent.com/xM8bzhN_pbFY8HyyglVe9XMaDRH5SGqkCnZvMEQ0B4653LkXqGT19k-Uqzv6OiB0LMVoKsRhuHOAh0E=w120-h120-l90-rj\', \'width\': 120, \'height\': 120}]}, \'thumbnailCrop\': \'MUSIC_THUMBNAIL_CROP_UNSPECIFIED\', \'thumbnailScale\': \'MUSIC_THUMBNAIL_SCALE_ASPECT_FIT\', \'trackingParams\': \'CCIQhL8CIhMI4ZTzmYqlhQMVA5TlBx23uAsa\'}}, \'overlay\': {\'musicItemThumbnailOverlayRenderer\': {\'background\': {\'verticalGradient\': {\'gradientLayerColors\': [\'3422552064\', \'3422552064\']}}, \'content\': {\'musicPlayButtonRenderer\': {\'playNavigationEndpoint\': {\'clickTrackingParams\': \'CCEQyN4CIhMI4ZTzmYqlhQMVA5TlBx23uAsa\', \'watchEndpoint\': {\'videoId\': \'hpSrLjc5SMs\', \'playlistId\': \'LM\', \'playlistSetVideoId\': \'56B44F6D10557CC6\', \'loggingContext\': {\'vssLoggingContext\': {\'serializedContextData\': \'GgJMTQ%3D%3D\'}}, \'watchEndpointMusicSupportedConfigs\': {\'watchEndpointMusicConfig\': {\'musicVideoType\': \'MUSIC_VIDEO_TYPE_ATV\'}}}}, \'trackingParams\': \'CCEQyN4CIhMI4ZTzmYqlhQMVA5TlBx23uAsa\', \'playIcon\': {\'iconType\': \'PLAY_ARROW\'}, \'pauseIcon\': {\'iconType\': \'PAUSE\'}, \'iconColor\': 4294967295, \'backgroundColor\': 0, \'activeBackgroundColor\': 0, \'loadingIndicatorColor\': 4294901760, \'playingIcon\': {\'iconType\': \'VOLUME_UP\'}, \'iconLoadingColor\': 0, \'activeScaleFactor\': 1, \'buttonSize\': \'MUSIC_PLAY_BUTTON_SIZE_SMALL\', \'rippleTarget\': \'MUSIC_PLAY_BUTTON_RIPPLE_TARGET_SELF\', \'accessibilityPlayData\': {\'accessibilityData\': {\'label\': \'Play Wonderwall - Oasis - 4 minutes, 19 seconds\'}}, \'accessibilityPauseData\': {\'accessibilityData\': {\'label\': \'Pause Wonderwall - Oasis - 4 minutes, 19 seconds\'}}}}, \'contentPosition\': \'MUSIC_ITEM_THUMBNAIL_OVERLAY_CONTENT_POSITION_CENTERED\', \'displayStyle\': \'MUSIC_ITEM_THUMBNAIL_OVERLAY_DISPLAY_STYLE_PERSISTENT\'}}, \'flexColumns\': [{\'musicResponsiveListItemFlexColumnRenderer\': {\'text\': {\'runs\': [{\'text\': \'Wonderwall\', \'navigationEndpoint\': {\'clickTrackingParams\': \'CBMQyfQCGAAiEwjhlPOZiqWFAxUDlOUHHbe4Cxo=\', \'watchEndpoint\': {\'videoId\': \'hpSrLjc5SMs\', \'playlistId\': \'LM\', \'loggingContext\': {\'vssLoggingContext\': {\'serializedContextData\': \'GgJMTQ%3D%3D\'}}, \'watchEndpointMusicSupportedConfigs\': {\'watchEndpointMusicConfig\': {\'musicVideoType\': \'MUSIC_VIDEO_TYPE_ATV\'}}}}}]}, \'displayPriority\': \'MUSIC_RESPONSIVE_LIST_ITEM_COLUMN_DISPLAY_PRIORITY_HIGH\'}}, {\'musicResponsiveListItemFlexColumnRenderer\': {\'text\': {\'runs\': [{\'text\': \'Oasis\', \'navigationEndpoint\': {\'clickTrackingParams\': \'CBMQyfQCGAAiEwjhlPOZiqWFAxUDlOUHHbe4Cxo=\', \'browseEndpoint\': {\'browseId\': \'UCmMUZbaYdNH0bEd1PAlAqsA\', \'browseEndpointContextSupportedConfigs\': {\'browseEndpointContextMusicConfig\': {\'pageType\': \'MUSIC_PAGE_TYPE_ARTIST\'}}}}}]}, \'displayPriority\': \'MUSIC_RESPONSIVE_LIST_ITEM_COLUMN_DISPLAY_PRIORITY_HIGH\'}}, {\'musicResponsiveListItemFlexColumnRenderer\': {\'text\': {\'runs\': [{\'text\': "(What\'s The Story) Morning Glory?", \'navigationEndpoint\': {\'clickTrackingParams\': \'CBMQyfQCGAAiEwjhlPOZiqWFAxUDlOUHHbe4Cxo=\', \'browseEndpoint\': {\'browseId\': \'MPREb_PITqkpE6ExP\', \'browseEndpointContextSupportedConfigs\': {\'browseEndpointContextMusicConfig\': {\'pageType\': \'MUSIC_PAGE_TYPE_ALBUM\'}}}}}]}, \'displayPriority\': \'MUSIC_RESPONSIVE_LIST_ITEM_COLUMN_DISPLAY_PRIORITY_MEDIUM\'}}], \'fixedColumns\': [{\'musicResponsiveListItemFixedColumnRenderer\': {\'text\': {\'runs\': [{\'text\': \'4:19\'}]}, \'displayPriority\': \'MUSIC_RESPONSIVE_LIST_ITEM_COLUMN_DISPLAY_PRIORITY_HIGH\', \'size\': \'MUSIC_RESPONSIVE_LIST_ITEM_FIXED_COLUMN_SIZE_SMALL\'}}], \'menu\': {\'menuRenderer\': {\'items\': [{\'menuNavigationItemRenderer\': {\'text\': {\'runs\': [{\'text\': \'Start radio\'}]}, \'icon\': {\'iconType\': \'MIX\'}, \'navigationEndpoint\': {\'clickTrackingParams\': \'CCAQm_MFGAAiEwjhlPOZiqWFAxUDlOUHHbe4Cxo=\', \'watchEndpoint\': {\'videoId\': \'hpSrLjc5SMs\', \'playlistId\': \'RDAMVMhpSrLjc5SMs\', \'params\': \'wAEB\', \'loggingContext\': {\'vssLoggingContext\': {\'serializedContextData\': \'GhFSREFNVk1ocFNyTGpjNVNNcw%3D%3D\'}}, \'watchEndpointMusicSupportedConfigs\': {\'watchEndpointMusicConfig\': {\'musicVideoType\': \'MUSIC_VIDEO_TYPE_ATV\'}}}}, \'trackingParams\': \'CCAQm_MFGAAiEwjhlPOZiqWFAxUDlOUHHbe4Cxo=\'}}, {\'menuServiceItemRenderer\': {\'text\': {\'runs\': [{\'text\': \'Play next\'}]}, \'icon\': {\'iconType\': \'QUEUE_PLAY_NEXT\'}, \'serviceEndpoint\': {\'clickTrackingParams\': \'CB4Qvu4FGAEiEwjhlPOZiqWFAxUDlOUHHbe4Cxo=\', \'queueAddEndpoint\': {\'queueTarget\': {\'videoId\': \'hpSrLjc5SMs\', \'onEmptyQueue\': {\'clickTrackingParams\': \'CB4Qvu4FGAEiEwjhlPOZiqWFAxUDlOUHHbe4Cxo=\', \'watchEndpoint\': {\'videoId\': \'hpSrLjc5SMs\'}}}, \'queueInsertPosition\': \'INSERT_AFTER_CURRENT_VIDEO\', \'commands\': [{\'clickTrackingParams\': \'CB4Qvu4FGAEiEwjhlPOZiqWFAxUDlOUHHbe4Cxo=\', \'addToToastAction\': {\'item\': {\'notificationTextRenderer\': {\'successResponseText\': {\'runs\': [{\'text\': \'Song will play next\'}]}, \'trackingParams\': \'CB8QyscDIhMI4ZTzmYqlhQMVA5TlBx23uAsa\'}}}}]}}, \'trackingParams\': \'CB4Qvu4FGAEiEwjhlPOZiqWFAxUDlOUHHbe4Cxo=\'}}, {\'menuServiceItemRenderer\': {\'text\': {\'runs\': [{\'text\': \'Add to queue\'}]}, \'icon\': {\'iconType\': \'ADD_TO_REMOTE_QUEUE\'}, \'serviceEndpoint\': {\'clickTrackingParams\': \'CBwQ--8FGAIiEwjhlPOZiqWFAxUDlOUHHbe4Cxo=\', \'queueAddEndpoint\': {\'queueTarget\': {\'videoId\': \'hpSrLjc5SMs\', \'onEmptyQueue\': {\'clickTrackingParams\': \'CBwQ--8FGAIiEwjhlPOZiqWFAxUDlOUHHbe4Cxo=\', \'watchEndpoint\': {\'videoId\': \'hpSrLjc5SMs\'}}}, \'queueInsertPosition\': \'INSERT_AT_END\', \'commands\': [{\'clickTrackingParams\': \'CBwQ--8FGAIiEwjhlPOZiqWFAxUDlOUHHbe4Cxo=\', \'addToToastAction\': {\'item\': {\'notificationTextRenderer\': {\'successResponseText\': {\'runs\': [{\'text\': \'Song added to queue\'}]}, \'trackingParams\': \'CB0QyscDIhMI4ZTzmYqlhQMVA5TlBx23uAsa\'}}}}]}}, \'trackingParams\': \'CBwQ--8FGAIiEwjhlPOZiqWFAxUDlOUHHbe4Cxo=\'}}, {\'toggleMenuServiceItemRenderer\': {\'defaultText\': {\'runs\': [{\'text\': \'Remove from library\'}]}, \'defaultIcon\': {\'iconType\': \'LIBRARY_SAVED\'}, \'defaultServiceEndpoint\': {\'clickTrackingParams\': \'CBsQhP8FGAMiEwjhlPOZiqWFAxUDlOUHHbe4Cxo=\', \'feedbackEndpoint\': {\'feedbackToken\': \'AB9zfpLPiCv3HHL4P4SoHsFTBYODVomNZM3aV35ISRqHY63nLHH2KP8AqiGjG7gr2ZB6PgJuDYFZ_yM7UdkUTY00sODMlbHWeg\'}}, \'toggledText\': {\'runs\': [{\'text\': \'Save to library\'}]}, \'toggledIcon\': {\'iconType\': \'LIBRARY_ADD\'}, \'toggledServiceEndpoint\': {\'clickTrackingParams\': \'CBsQhP8FGAMiEwjhlPOZiqWFAxUDlOUHHbe4Cxo=\', \'feedbackEndpoint\': {\'feedbackToken\': \'AB9zfpJkrlCs0SRN1_UDiOltt1QwVAzya3eaRkB7Id1QpvaopGNxCPS5aYtLcK2hbp070X7lR-5n32FPumBlMgGjrS8QDA-ItA\'}}, \'trackingParams\': \'CBsQhP8FGAMiEwjhlPOZiqWFAxUDlOUHHbe4Cxo=\'}}, {\'menuNavigationItemRenderer\': {\'text\': {\'runs\': [{\'text\': \'Save to playlist\'}]}, \'icon\': {\'iconType\': \'ADD_TO_PLAYLIST\'}, \'navigationEndpoint\': {\'clickTrackingParams\': \'CBoQw5QGGAQiEwjhlPOZiqWFAxUDlOUHHbe4Cxo=\', \'addToPlaylistEndpoint\': {\'videoId\': \'hpSrLjc5SMs\'}}, \'trackingParams\': \'CBoQw5QGGAQiEwjhlPOZiqWFAxUDlOUHHbe4Cxo=\'}}, {\'menuServiceItemRenderer\': {\'text\': {\'runs\': [{\'text\': \'Remove from playlist\'}]}, \'icon\': {\'iconType\': \'REMOVE_FROM_PLAYLIST\'}, \'serviceEndpoint\': {\'clickTrackingParams\': \'CBUQpzsiEwjhlPOZiqWFAxUDlOUHHbe4Cxo=\', \'likeEndpoint\': {\'status\': \'INDIFFERENT\', \'target\': {\'videoId\': \'hpSrLjc5SMs\'}, \'actions\': [{\'clickTrackingParams\': \'CBUQpzsiEwjhlPOZiqWFAxUDlOUHHbe4Cxo=\', \'hideEnclosingAction\': {\'hack\': True}}]}}, \'trackingParams\': \'CBUQpzsiEwjhlPOZiqWFAxUDlOUHHbe4Cxo=\'}}, {\'menuNavigationItemRenderer\': {\'text\': {\'runs\': [{\'text\': \'Go to album\'}]}, \'icon\': {\'iconType\': \'ALBUM\'}, \'navigationEndpoint\': {\'clickTrackingParams\': \'CBkQj_sFGAYiEwjhlPOZiqWFAxUDlOUHHbe4Cxo=\', \'browseEndpoint\': {\'browseId\': \'MPREb_PITqkpE6ExP\', \'browseEndpointContextSupportedConfigs\': {\'browseEndpointContextMusicConfig\': {\'pageType\': \'MUSIC_PAGE_TYPE_ALBUM\'}}}}, \'trackingParams\': \'CBkQj_sFGAYiEwjhlPOZiqWFAxUDlOUHHbe4Cxo=\'}}, {\'menuNavigationItemRenderer\': {\'text\': {\'runs\': [{\'text\': \'Go to artist\'}]}, \'icon\': {\'iconType\': \'ARTIST\'}, \'navigationEndpoint\': {\'clickTrackingParams\': \'CBgQkPsFGAciEwjhlPOZiqWFAxUDlOUHHbe4Cxo=\', \'browseEndpoint\': {\'browseId\': \'UCmMUZbaYdNH0bEd1PAlAqsA\', \'browseEndpointContextSupportedConfigs\': {\'browseEndpointContextMusicConfig\': {\'pageType\': \'MUSIC_PAGE_TYPE_ARTIST\'}}}}, \'trackingParams\': \'CBgQkPsFGAciEwjhlPOZiqWFAxUDlOUHHbe4Cxo=\'}}, {\'menuNavigationItemRenderer\': {\'text\': {\'runs\': [{\'text\': \'Share\'}]}, \'icon\': {\'iconType\': \'SHARE\'}, \'navigationEndpoint\': {\'clickTrackingParams\': \'CBcQkfsFGAgiEwjhlPOZiqWFAxUDlOUHHbe4Cxo=\', \'shareEntityEndpoint\': {\'serializedShareEntity\': \'CgtocFNyTGpjNVNNcw%3D%3D\', \'sharePanelType\': \'SHARE_PANEL_TYPE_UNIFIED_SHARE_PANEL\'}}, \'trackingParams\': \'CBcQkfsFGAgiEwjhlPOZiqWFAxUDlOUHHbe4Cxo=\'}}], \'trackingParams\': \'CBUQpzsiEwjhlPOZiqWFAxUDlOUHHbe4Cxo=\', \'topLevelButtons\': [{\'likeButtonRenderer\': {\'target\': {\'videoId\': \'hpSrLjc5SMs\'}, \'likeStatus\': \'LIKE\', \'trackingParams\': \'CBYQpUEYCSITCOGU85mKpYUDFQOU5Qcdt7gLGg==\', \'likesAllowed\': True, \'serviceEndpoints\': [{\'clickTrackingParams\': \'CBYQpUEYCSITCOGU85mKpYUDFQOU5Qcdt7gLGg==\', \'likeEndpoint\': {\'status\': \'LIKE\', \'target\': {\'videoId\': \'hpSrLjc5SMs\'}, \'actions\': [{\'clickTrackingParams\': \'CBYQpUEYCSITCOGU85mKpYUDFQOU5Qcdt7gLGg==\', \'musicLibraryStatusUpdateCommand\': {\'libraryStatus\': \'MUSIC_LIBRARY_STATUS_IN_LIBRARY\', \'addToLibraryFeedbackToken\': \'AB9zfpJkrlCs0SRN1_UDiOltt1QwVAzya3eaRkB7Id1QpvaopGNxCPS5aYtLcK2hbp070X7lR-5n32FPumBlMgGjrS8QDA-ItA\'}}]}}, {\'clickTrackingParams\': \'CBYQpUEYCSITCOGU85mKpYUDFQOU5Qcdt7gLGg==\', \'likeEndpoint\': {\'status\': \'DISLIKE\', \'target\': {\'videoId\': \'hpSrLjc5SMs\'}}}, {\'clickTrackingParams\': \'CBYQpUEYCSITCOGU85mKpYUDFQOU5Qcdt7gLGg==\', \'likeEndpoint\': {\'status\': \'INDIFFERENT\', \'target\': {\'videoId\': \'hpSrLjc5SMs\'}}}]}}], \'accessibility\': {\'accessibilityData\': {\'label\': \'Action menu\'}}}}, \'playlistItemData\': {\'playlistSetVideoId\': \'56B44F6D10557CC6\', \'videoId\': \'hpSrLjc5SMs\'}, \'multiSelectCheckbox\': {\'checkboxRenderer\': {\'onSelectionChangeCommand\': {\'clickTrackingParams\': \'CBQQvr4JIhMI4ZTzmYqlhQMVA5TlBx23uAsa\', \'updateMultiSelectStateCommand\': {\'multiSelectParams\': \'CAISAkxN\', \'multiSelectItem\': \'Ch8KC2hwU3JMamM1U01zEhA1NkI0NEY2RDEwNTU3Q0M2\'}}, \'checkedState\': \'CHECKBOX_CHECKED_STATE_UNCHECKED\', \'trackingParams\': \'CBQQvr4JIhMI4ZTzmYqlhQMVA5TlBx23uAsa\'}}}}], \'collapsedItemCount\': 1, \'trackingParams\': \'CBIQ9-MCGAAiEwjhlPOZiqWFAxUDlOUHHbe4Cxo=\', \'contentsMultiSelectable\': True}}], \'trackingParams\': \'CBEQui8iEwjhlPOZiqWFAxUDlOUHHbe4Cxo=\'}}, \'tabs\': [{\'tabRenderer\': {\'content\': {\'sectionListRenderer\': {\'contents\': [{\'musicResponsiveHeaderRenderer\': {\'thumbnail\': {\'musicThumbnailRenderer\': {\'thumbnail\': {\'thumbnails\': [{\'url\': \'https://www.gstatic.com/youtube/media/ytm/images/pbg/liked-music-@192.png\', \'width\': 192, \'height\': 192}, {\'url\': \'https://www.gstatic.com/youtube/media/ytm/images/pbg/liked-music-@576.png\', \'width\': 576, \'height\': 576}, {\'url\': \'https://www.gstatic.com/youtube/media/ytm/images/pbg/liked-music-@1200.png\', \'width\': 1200, \'height\': 1200}]}, \'thumbnailCrop\': \'MUSIC_THUMBNAIL_CROP_UNSPECIFIED\', \'thumbnailScale\': \'MUSIC_THUMBNAIL_SCALE_UNSPECIFIED\', \'trackingParams\': \'CBAQhL8CIhMI4ZTzmYqlhQMVA5TlBx23uAsa\'}}, \'buttons\': [{\'buttonRenderer\': {\'style\': \'STYLE_DARK_ON_WHITE\', \'size\': \'SIZE_DEFAULT\', \'icon\': {\'iconType\': \'MUSIC_SHUFFLE\'}, \'navigationEndpoint\': {\'clickTrackingParams\': \'CA8Q8FsYACITCOGU85mKpYUDFQOU5Qcdt7gLGg==\', \'watchPlaylistEndpoint\': {\'playlistId\': \'LM\', \'params\': \'wAEB8gECKAE%3D\'}}, \'accessibility\': {\'label\': \'Shuffle\'}, \'trackingParams\': \'CA8Q8FsYACITCOGU85mKpYUDFQOU5Qcdt7gLGg==\', \'accessibilityData\': {\'accessibilityData\': {\'label\': \'Shuffle\'}}}}, {\'musicPlayButtonRenderer\': {\'playNavigationEndpoint\': {\'clickTrackingParams\': \'CA4QyN4CGAEiEwjhlPOZiqWFAxUDlOUHHbe4Cxo=\', \'watchEndpoint\': {\'videoId\': \'hpSrLjc5SMs\', \'playlistId\': \'LM\', \'params\': \'wAEB\', \'loggingContext\': {\'vssLoggingContext\': {\'serializedContextData\': \'GgJMTQ%3D%3D\'}}, \'watchEndpointMusicSupportedConfigs\': {\'watchEndpointMusicConfig\': {\'musicVideoType\': \'MUSIC_VIDEO_TYPE_ATV\'}}}}, \'trackingParams\': \'CA4QyN4CGAEiEwjhlPOZiqWFAxUDlOUHHbe4Cxo=\', \'playIcon\': {\'iconType\': \'PLAY_ARROW\'}, \'pauseIcon\': {\'iconType\': \'PAUSE\'}, \'iconColor\': 4294967295, \'backgroundColor\': 0, \'activeBackgroundColor\': 0, \'loadingIndicatorColor\': 4294901760, \'playingIcon\': {\'iconType\': \'PAUSE\'}, \'iconLoadingColor\': 0, \'activeScaleFactor\': 1, \'accessibilityPlayData\': {\'accessibilityData\': {\'label\': \'Play Liked Music\'}}, \'accessibilityPauseData\': {\'accessibilityData\': {\'label\': \'Pause Liked Music\'}}}}, {\'menuRenderer\': {\'items\': [{\'menuNavigationItemRenderer\': {\'text\': {\'runs\': [{\'text\': \'Start radio\'}]}, \'icon\': {\'iconType\': \'MIX\'}, \'navigationEndpoint\': {\'clickTrackingParams\': \'CA0Qm_MFGAAiEwjhlPOZiqWFAxUDlOUHHbe4Cxo=\', \'watchPlaylistEndpoint\': {\'playlistId\': \'RDAMPLLM\', \'params\': \'wAEB\'}}, \'trackingParams\': \'CA0Qm_MFGAAiEwjhlPOZiqWFAxUDlOUHHbe4Cxo=\'}}, {\'menuServiceItemRenderer\': {\'text\': {\'runs\': [{\'text\': \'Play next\'}]}, \'icon\': {\'iconType\': \'QUEUE_PLAY_NEXT\'}, \'serviceEndpoint\': {\'clickTrackingParams\': \'CAsQvu4FGAEiEwjhlPOZiqWFAxUDlOUHHbe4Cxo=\', \'queueAddEndpoint\': {\'queueTarget\': {\'playlistId\': \'LM\', \'onEmptyQueue\': {\'clickTrackingParams\': \'CAsQvu4FGAEiEwjhlPOZiqWFAxUDlOUHHbe4Cxo=\', \'watchEndpoint\': {\'playlistId\': \'LM\'}}}, \'queueInsertPosition\': \'INSERT_AFTER_CURRENT_VIDEO\', \'commands\': [{\'clickTrackingParams\': \'CAsQvu4FGAEiEwjhlPOZiqWFAxUDlOUHHbe4Cxo=\', \'addToToastAction\': {\'item\': {\'notificationTextRenderer\': {\'successResponseText\': {\'runs\': [{\'text\': \'Playlist will play next\'}]}, \'trackingParams\': \'CAwQyscDIhMI4ZTzmYqlhQMVA5TlBx23uAsa\'}}}}]}}, \'trackingParams\': \'CAsQvu4FGAEiEwjhlPOZiqWFAxUDlOUHHbe4Cxo=\'}}, {\'menuServiceItemRenderer\': {\'text\': {\'runs\': [{\'text\': \'Add to queue\'}]}, \'icon\': {\'iconType\': \'ADD_TO_REMOTE_QUEUE\'}, \'serviceEndpoint\': {\'clickTrackingParams\': \'CAkQ--8FGAIiEwjhlPOZiqWFAxUDlOUHHbe4Cxo=\', \'queueAddEndpoint\': {\'queueTarget\': {\'playlistId\': \'LM\', \'onEmptyQueue\': {\'clickTrackingParams\': \'CAkQ--8FGAIiEwjhlPOZiqWFAxUDlOUHHbe4Cxo=\', \'watchEndpoint\': {\'playlistId\': \'LM\'}}}, \'queueInsertPosition\': \'INSERT_AT_END\', \'commands\': [{\'clickTrackingParams\': \'CAkQ--8FGAIiEwjhlPOZiqWFAxUDlOUHHbe4Cxo=\', \'addToToastAction\': {\'item\': {\'notificationTextRenderer\': {\'successResponseText\': {\'runs\': [{\'text\': \'Playlist added to queue\'}]}, \'trackingParams\': \'CAoQyscDIhMI4ZTzmYqlhQMVA5TlBx23uAsa\'}}}}]}}, \'trackingParams\': \'CAkQ--8FGAIiEwjhlPOZiqWFAxUDlOUHHbe4Cxo=\'}}], \'trackingParams\': \'CAgQpzsYAiITCOGU85mKpYUDFQOU5Qcdt7gLGg==\', \'accessibility\': {\'accessibilityData\': {\'label\': \'Action menu\'}}}}], \'title\': {\'runs\': [{\'text\': \'Liked Music\'}]}, \'subtitle\': {\'runs\': [{\'text\': \'Auto playlist\'}, {\'text\': \' • \'}, {\'text\': \'2024\'}]}, \'trackingParams\': \'CAQQneEIGAAiEwjhlPOZiqWFAxUDlOUHHbe4Cxo=\', \'straplineTextOne\': {\'runs\': [{\'text\': \'Test Brand Account\', \'navigationEndpoint\': {\'clickTrackingParams\': \'CAQQneEIGAAiEwjhlPOZiqWFAxUDlOUHHbe4Cxo=\', \'browseEndpoint\': {\'browseId\': \'UCXPN0pLNt7zVISrKI0GTGjQ\', \'browseEndpointContextSupportedConfigs\': {\'browseEndpointContextMusicConfig\': {\'pageType\': \'MUSIC_PAGE_TYPE_USER_CHANNEL\'}}}}}]}, \'straplineThumbnail\': {\'musicThumbnailRenderer\': {\'thumbnail\': {\'thumbnails\': [{\'url\': \'https://yt3.ggpht.com/ytc/AIdro_nxtL3ySB12P2y9olwu2T9iBWv_rJMABQwq9t6xnpbqA-Ze72VmWtoDr6va5n50=s48-c-k-c0x00000000-no-cc-rj-rp\', \'width\': 48, \'height\': 48}, {\'url\': \'https://yt3.ggpht.com/ytc/AIdro_nxtL3ySB12P2y9olwu2T9iBWv_rJMABQwq9t6xnpbqA-Ze72VmWtoDr6va5n50=s96-c-k-c0x00000000-no-cc-rj-rp\', \'width\': 96, \'height\': 96}]}, \'thumbnailCrop\': \'MUSIC_THUMBNAIL_CROP_UNSPECIFIED\', \'thumbnailScale\': \'MUSIC_THUMBNAIL_SCALE_UNSPECIFIED\', \'trackingParams\': \'CAcQhL8CIhMI4ZTzmYqlhQMVA5TlBx23uAsa\'}}, \'description\': {\'musicDescriptionShelfRenderer\': {\'description\': {\'runs\': [{\'text\': \'Music you like in any YouTube app will show here. You can change this in Settings.\'}]}, \'moreButton\': {\'toggleButtonRenderer\': {\'isToggled\': False, \'isDisabled\': False, \'defaultIcon\': {\'iconType\': \'EXPAND\'}, \'defaultText\': {\'runs\': [{\'text\': \'More\'}]}, \'toggledIcon\': {\'iconType\': \'COLLAPSE\'}, \'toggledText\': {\'runs\': [{\'text\': \'Less\'}]}, \'trackingParams\': \'CAYQmE0iEwjhlPOZiqWFAxUDlOUHHbe4Cxo=\'}}, \'trackingParams\': \'CAUQiPgDIhMI4ZTzmYqlhQMVA5TlBx23uAsa\', \'shelfStyle\': \'MUSIC_SHELF_STYLE_OPEN_DIALOG_ON_CLICK\'}}, \'secondSubtitle\': {\'runs\': [{\'text\': \'1 song\'}, {\'text\': \' • \'}, {\'text\': \'4 minutes, 19 seconds\'}]}}}], \'trackingParams\': \'CAMQui8iEwjhlPOZiqWFAxUDlOUHHbe4Cxo=\'}}, \'trackingParams\': \'CAIQ8JMBGAAiEwjhlPOZiqWFAxUDlOUHHbe4Cxo=\'}}]}}, exception: \'singleColumnBrowseResultsRenderer\''
```

**Comment by sigma67** [comment] 2024-04-03 07:01
duplicate of #562

**Closed by sigma67** 2024-04-03 07:01 UTC
