### ISSUE TITLE
get_watch_playlist() fails with 404: Requested entity not found

### ISSUE THREAD

**Issue by spectreseven1138** [sigma67/ytmusicapi#296] opened 2022-09-19 15:11 UTC
A project I'm working on involving ytmusicapi suddenly stopped working today. Whenever get_watch_playlist is called it fails with the following error regardless of whether the client is authenticated:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/.local/lib/python3.10/site-packages/ytmusicapi/mixins/watch.py", line 120, in get_watch_playlist
    response = self._send_request(endpoint, body)
  File "~/.local/lib/python3.10/site-packages/ytmusicapi/ytmusic.py", line 144, in _send_request
    raise Exception(message + error)
Exception: Server returned HTTP 404: Not Found.
Requested entity was not found.
``` 
I've tried multiple valid ids, invalid ids, and using a VPN, none of which seem to make a difference. Other functions like search seem to work fine, and YouTube Music works as usual in a browser.

**Comment by simu** [comment] 2022-09-19 15:58
From what I've found the issue can be resolved by changing https://github.com/sigma67/ytmusicapi/blob/20b4631c31b65d5d40caf89b5db5fd661e82a979/ytmusicapi/helpers.py#L26 to `1.20220912.01.00` (as found when inspecting traffic generated by the web app).

Since there's a date in the new version string, I wonder whether this may need to be dynamically updated when new versions of the app are released.

**Comment by MarvinSchenkel** [comment] 2022-09-19 18:32
> ytmusicapi/ytmusicapi/helpers.py

Does this actually work for you? I tried the suggested change, but I still get the same 404 error.

**Comment by simu** [comment] 2022-09-19 18:39
> Does this actually work for you? I tried the suggested change, but I still get the same 404 error.

Yes, it worked for me (approximately 10 hours ago), however I'm not 100% if that ended up being the only change that I had to make (I'll have to check that tomorrow). Additionally, I also used a fresh cookie copied from the web app today.

**Comment by MarvinSchenkel** [comment] 2022-09-20 06:52
Guess what, this morning my `get_watch_playlist` started working again, even without the change of `clientVersion`.  Did YT Music revert some changes on their side?

**Comment by sigma67** [comment] 2022-09-20 07:28
Might have been some sort of A/B testing? I cannot reproduce the error currently.

We may need to find a way to dynamically get a viable `clientVersion` if this turns out to be the cause.

**Comment by simu** [comment] 2022-09-20 11:08
> Might have been some sort of A/B testing? I cannot reproduce the error currently.

Looks like it, I can't reproduce it anymore either (side-note: the web app has version `1.20220914.01.00` for me today).

> >  Does this actually work for you? I tried the suggested change, but I still get the same 404 error.
>
> Yes, it worked for me (approximately 10 hours ago), however I'm not 100% if that ended up being the only change that I had to make (I'll have to check that tomorrow).

I checked again, the only change I made yesterday (after some trial and error) was setting the `clientVersion` to the value if found in the web app.

**Comment by sigma67** [comment] 2022-10-01 13:42
Seems to be resolved for now, can reopen if needed in the future.

**Closed by sigma67** 2022-10-01 13:42 UTC
Labels: yt-update
