### ISSUE TITLE
Error getting play list

### ISSUE THREAD

**Issue by Sleeepy2** [sigma67/ytmusicapi#129] opened 2020-12-18 14:01 UTC
Just and FYI

2020-12-18 08:55:56 ERROR (SyncWorker_5) [custom_components.ytube_music_player.media_player] 
============= ytube_music_player Integration Error ================
2020-12-18 08:55:56 ERROR (SyncWorker_5) [custom_components.ytube_music_player.media_player] unfortunately we hit an error in the sub api, please open a ticket at
2020-12-18 08:55:56 ERROR (SyncWorker_5) [custom_components.ytube_music_player.media_player] https://github.com/sigma67/ytmusicapi/issues
2020-12-18 08:55:56 ERROR (SyncWorker_5) [custom_components.ytube_music_player.media_player] and paste the following output:

2020-12-18 08:55:56 ERROR (SyncWorker_5) [custom_components.ytube_music_player.media_player] Traceback (most recent call last):
  File "/config/custom_components/ytube_music_player/media_player.py", line 484, in _load_playlist
    my_radio = self._api.get_playlist(playlistId = self._playlists[idx]['playlistId'], limit = int(self._playlists[idx]['count']))['tracks']
  File "/usr/local/lib/python3.8/site-packages/ytmusicapi/mixins/playlists.py", line 91, in get_playlist
    song_count = to_int(
  File "/usr/local/lib/python3.8/site-packages/ytmusicapi/helpers.py", line 71, in to_int
    return locale.atoi(number)
  File "/usr/local/lib/python3.8/locale.py", line 330, in atoi
    return int(delocalize(string))
ValueError: invalid literal for int() with base 10: '2,828'

2020-12-18 08:55:56 ERROR (SyncWorker_5) [custom_components.ytube_music_player.media_player] 
thanks, Kolja
2020-12-18 08:55:56 ERROR (SyncWorker_5) [custom_components.ytube_music_player.media_player] ============= ytube_music_player Integration Error ================

**Comment by sigma67** [comment] 2020-12-18 14:06
This seems to be a duplicate of #125? Please close if it is

**Closed** 2020-12-18 14:09 UTC
