### ISSUE TITLE
trackCount dictionary key from YTMusic.get_playlist returns 1 

### ISSUE THREAD

**Issue by ladymileva** [sigma67/ytmusicapi#658] opened 2024-10-07 14:05 UTC
Thank you so much for the ytmusicapi, I used it for a script that removes the currently playing song from a playlist.  

For one of my playlists (it is working as expected for all the others) the trackCount dictionary key from YTMusic.get_playlist returns 1.  

To reproduce: 
from ytmusicapi.ytmusic import YTMusic
<authenticate>
playlistId = <'id_string'>
playlist = ytmusic.get_playlist(playlistId,None)
trackCount = playlist.get('trackCount')

trackCount always equals 1 for this playlist, even if I specify a value instead of "None" for the number of tracks to retrieve info for.  

I can retrieve the proper track count by using: 
trackinfo = playlist.get('tracks') 
trackCount = len(trackinfo)

I'm not sure why this playlist behaves differently than the others.  It may helpful to note that the playlist was created over a year ago, has over 1000 tracks, and the playlistId end with an underscore.

**Comment by sigma67** [comment] 2024-10-07 16:57
this has been fixed already, duplicate of https://github.com/sigma67/ytmusicapi/issues/650

**Closed by sigma67** 2024-10-07 16:57 UTC
