### ISSUE TITLE
First artist of a song is missing when searching

### ISSUE THREAD

**Issue by garaevdi** [sigma67/ytmusicapi#519] opened 2024-01-14 04:16 UTC
When doing a global search, first song's artist is missing, but songs only search (i.e. `search(query, "songs")`) returns both artist. Also if song has only one artist, search simply returns empty array.

Search query I used: `big city life mattafix remix`, but from my testing any query will work.

<details><summary>Results</summary>
<p>

related block of `ytmisuc.search("big city life mattafix remix")`
```
  {
    "category": "Songs",
    "resultType": "song",
    "title": "Big City Life (Odd Mob Extended Remix)",
    "album": {
      "name": "Big City Life (Odd Mob Extended Remix)",
      "id": "MPREb_gHMuMzGHA4J"
    },
    "inLibrary": false,
    "feedbackTokens": {
      "add": null,
      "remove": null
    },
    "videoId": "aZbLyoVQvrc",
    "videoType": "MUSIC_VIDEO_TYPE_ATV",
    "duration": "3:13",
    "year": null,
    "artists": [
      {
        "name": "Mattafix",
        "id": "UCTLiNbjjXqrxJ7o7pTyCrTQ"
      }
    ],
    "duration_seconds": 193,
    "isExplicit": false,
    "thumbnails": [
      {
        "url": "https://lh3.googleusercontent.com/8aqmOXtM24i8h7O-P2wx7osIzG-HPXRYLgzPe5RiP5DcS6eXpjOdlI5BOhdlqki0jFJzrLO_65ebP0sZ=w60-h60-l90-rj",
        "width": 60,
        "height": 60
      },
      {
        "url": "https://lh3.googleusercontent.com/8aqmOXtM24i8h7O-P2wx7osIzG-HPXRYLgzPe5RiP5DcS6eXpjOdlI5BOhdlqki0jFJzrLO_65ebP0sZ=w120-h120-l90-rj",
        "width": 120,
        "height": 120
      }
    ]
  },
  {
    "category": "Songs",
    "resultType": "song",
    "title": "Big City Life",
    "album": {
      "name": "Ultimate R&B 2007",
      "id": "MPREb_TbVw8hM2wZg"
    },
    "inLibrary": false,
    "feedbackTokens": {
      "add": null,
      "remove": null
    },
    "videoId": "62YNFuepRII",
    "videoType": "MUSIC_VIDEO_TYPE_ATV",
    "duration": "3:57",
    "year": null,
    "artists": [],
    "duration_seconds": 237,
    "isExplicit": false,
    "thumbnails": [
      {
        "url": "https://lh3.googleusercontent.com/mE2dfd9oo5FFyzlAjZTN10vVAZYMrXzuQqG0LHRu8pV-kMYR2Uz3tDUyXpgy9etRvdN17nT84D06kPkY=w60-h60-s-l90-rj",
        "width": 60,
        "height": 60
      },
      {
        "url": "https://lh3.googleusercontent.com/mE2dfd9oo5FFyzlAjZTN10vVAZYMrXzuQqG0LHRu8pV-kMYR2Uz3tDUyXpgy9etRvdN17nT84D06kPkY=w120-h120-s-l90-rj",
        "width": 120,
        "height": 120
      }
    ]
  },
  {
    "category": "Songs",
    "resultType": "song",
    "title": "Big City Life",
    "album": {
      "name": "\u04d8\u043b\u0456\u043f\u043f\u0435",
      "id": "MPREb_Q3Q6HkcbUqf"
    },
    "inLibrary": false,
    "feedbackTokens": {
      "add": null,
      "remove": null
    },
    "videoId": "89qWVWDJhxc",
    "videoType": "MUSIC_VIDEO_TYPE_ATV",
    "duration": "4:25",
    "year": null,
    "artists": [
      {
        "name": "De Lacure",
        "id": "UC_ZoP74tMehunqxY_Xl0f0A"
      }
    ],
    "duration_seconds": 265,
    "isExplicit": false,
    "thumbnails": [
      {
        "url": "https://lh3.googleusercontent.com/TJAf52t0wXHdoR0Lf6wd-TyLz7203apAM5VrNx2BodhBq9ZDTku2L-JBptS1hwWgn8TOeQZfqc4CqNMT=w60-h60-l90-rj",
        "width": 60,
        "height": 60
      },
      {
        "url": "https://lh3.googleusercontent.com/TJAf52t0wXHdoR0Lf6wd-TyLz7203apAM5VrNx2BodhBq9ZDTku2L-JBptS1hwWgn8TOeQZfqc4CqNMT=w120-h120-l90-rj",
        "width": 120,
        "height": 120
      }
    ]
  },

```

And the same on ytmusic itself
![image](https://github.com/sigma67/ytmusicapi/assets/64484944/aa2a8791-d63a-4da2-9600-9df171019980)

</p>
</details>

**Comment by sigma67** [comment] 2024-01-14 13:49
duplicate of #518

**Closed by sigma67** 2024-01-14 13:49 UTC
Labels: bug
